### ISSUE TITLE
Create compatible UUID using SQL/MySQL functions

### ISSUE THREAD

**Issue by jonagoldman** [fab2s/SoUuid#3]
First of all thanks for this package. I find it useful and think it deserves more attention from the PHP community.

I am storing UUIDs in base62 as it seems a good balance between performance and readability.

I want to know if there is a way (at least in theory) to generate compatible UUIDs using SQL built in functions only. This will allow to insert large amounts of records without the need to iterate and generate them using the PHP methods provided by this package, resulting in very fast inserts.

Thanks.

**Comment by fab2s** [comment]
You're welcome ;)

Anyway, have you had a look at both links posted in the readme ?
https://www.percona.com/blog/2014/12/19/store-uuid-optimized-way/
https://mariadb.com/kb/en/library/guiduuid-performance/

They both include procedure / function to auto generate UUID1. Now I'm not sure it is entirely possible, but you should be able to generate a SoUuid using mysql function, all that is needed is a strong rand and a time in micro second (TIMESTAMP can do that so) and few string manipulations.

Now thinking about use cases, I would think you are dealing with some type of migration, because if you where to generate each record, the overhead of SoUuid would be minimal already. In such case you still got the option to either slowly fill an new SoUuid column in the old db/table and dump it / import it or alter it once done.

You could also imagine to write a small script ([YaEtl](https://github.com/fab2s/YaEtl) has everything needed to make it quick to write) that would generate bulk inserts with the proper SoUuid generated. That should be pretty fast if you can use multi inserts and disable indexes in the target table during the operation.

**Comment by jonagoldman** [comment]
Thanks, will give it a try, closing for now.
